name: Trigger All

on:
  workflow_dispatch:

permissions:
  contents: write # 用于 checkout & API 调用
  actions: write # 用于触发其它 workflows

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger triggered1.yml
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'triggered1.yml',  // 或者 workflow 文件名对应的 workflow_id
              ref: 'main'
            });

      - name: Trigger triggered2.yml
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'triggered2.yml',
              ref: 'main'
            });
